### ISSUE TITLE
可否增加ipset支持？

### ISSUE THREAD

**Issue by ltu00** [RuralHunter/CoreELEC#10]
官方的不支持ipset，可否增加下？

**Comment by RuralHunter** [comment]
等下个版本吧

**Comment by RuralHunter** [comment]
链接: https://pan.baidu.com/s/1TZFriombQVYYlYcmxcOTNw 提取码: jbib
这个升级包你试一下，一样放在/storage/.update/下面重启就行。

**Comment by ihuohua** [comment]
> 链接: https://pan.baidu.com/s/1TZFriombQVYYlYcmxcOTNw 提取码: jbib
> 这个升级包你试一下，一样放在/storage/.update/下面重启就行。

大神，你好！请问N1的CoreELEC的内核都是3.1.4版本吗

**Comment by RuralHunter** [comment]
目前都是3.14
