### ISSUE TITLE
放在storage/.update下重启后无法更新。

### ISSUE THREAD

**Issue by ligbang** [RuralHunter/CoreELEC#11]
放在storage/.update下重启后无法更新，是什么原因,n1之前是9.2 刷入了emmc

**Comment by RuralHunter** [comment]
老版本是我的版本吗？别人定制的版本可能去掉了这个功能

**Comment by callmesoul** [comment]
我恩山刷的9.2.0版本 然后把最新的9.2.5放到了storage / .update下也不可以升级啊，要怎么升级呢？ ?

**Comment by RuralHunter** [comment]
ls -l /storage/.update/*.tar
上面这条命令如果能看见升级文件，那就说明你刷的版本把升级功能禁掉了。

**Comment by callmesoul** [comment]
确实能看见，
昨天直接拿你最新版本重刷了，usb刷没问题，刷入ec后重启就卡在开机画面了（之前旧版本9.2.0是已经刷入ec）,要怎样才能重新将你的系统刷入ec

**Comment by RuralHunter** [comment]
我的版本不支持刷入emmc，只支持usb

**Comment by callmesoul** [comment]
噢噢，难怪，但是在恩山论坛好像有人用的你加一个n1_autoscript文件说可以刷入emmc，
https://www.right.com.cn/forum/forum.php?mod=viewthread&tid=4057253&extra=page%3D3%26filter%3Dtypeid%26typeid%3D21
