### ISSUE TITLE
可否将coreelec刷入emmc中

### ISSUE THREAD

**Issue by flamingo7777** [RuralHunter/CoreELEC#13]
首先感谢大神们的辛苦付出，其次，想提一个请求，就是将coreelec刷入emmc中，usb是2.0的，整体系统的运行速度是肯定受影响的，现在我是通过coreelec+docker+openwrt，可能后续还能搞个qbtorrent下载，这样肯定需要用到usb接口，因为遥控器是无法控制关机的，索性就不关机了，这样系统可以边做旁路由，边做下载机，边做播放机，当然理想很丰满，现实很骨感，大神们说不能刷入emmc肯定有原因，也希望大神们群策群力，在后续的版本中实现这个功能！最后，再次感谢大神们的辛苦付出！

**Comment by flyfishes** [comment]
参考这个，可以写入emmc。
https://www.right.com.cn/forum/thread-3944380-1-1.html

**Comment by flamingo7777** [comment]
> 参考这个，可以写入emmc。
> 
> https://www.right.com.cn/forum/thread-3944380-1-1.html
> 
> 

参照这个教程已经刷成功了，感谢！

**Comment by fireflycao** [comment]
请问怎么升级呢？
