### ISSUE TITLE
9.2.2 9.2.1怎么启动不了？

### ISSUE THREAD

**Issue by wellcomez** [RuralHunter/CoreELEC#14]
使用重启app apk，第一次会进去recovery菜单
尝过多个版本，9.0.0不是你处下载基本可以稳定启动
使用9.2.1成功一次
使用9.2.2从未成功

原因是启动脚本参数还是什么原因？

**Comment by wellcomez** [comment]
使用其他途径获得9.0.0使用的autoscript 貌似可以

**Comment by RuralHunter** [comment]
建议用其它支持这个app的版本
