### ISSUE TITLE
9.22为什么还是不能启动Docker的openwrt中的SSR P+?

### ISSUE THREAD

**Issue by canyxp** [RuralHunter/CoreELEC#15]
看说明是内核加入IPSET了，为什么还是不能正常启动？降级内核为momokind编译的9.02可正常启动SSR P+.

**Comment by RuralHunter** [comment]
ipset是9.22发布以后才加入的。需要的话可以自己升级：
链接: https://pan.baidu.com/s/1TZFriombQVYYlYcmxcOTNw 提取码: jbib
