### ISSUE TITLE
大家youtube ios投屏有成功的吗？

### ISSUE THREAD

**Issue by t66y100** [RuralHunter/CoreELEC#19]
设置 服务 里作如下图设置，iphone显示投屏成功，但是电视转两次圈，并没有画面也没有声音。
有没有投屏成功的？
![捕获](https://user-images.githubusercontent.com/63218433/88479592-d5546f00-cf82-11ea-9937-aec305cfd329.PNG)

**Comment by flamingo7777** [comment]
我爱奇艺能正常投屏，就说服务里面的都勾选下就好了

**Comment by RuralHunter** [comment]
kodi暂时不支持ios新版本的投屏了。

**Comment by t66y100** [comment]
感谢回复，已改用tubio等其他软件来投屏youtube
