### ISSUE TITLE
Bluetooth devices' configuration cann't be saved

### ISSUE THREAD

**Issue by lonecrane** [RuralHunter/CoreELEC#21]
I installed CoreELEC 9.2.3 on a USB flash driver, which is the well-known make of Sandisc.
The apparent problem is that all the bluetooth devices need re-pair after reboot Coreelec.
By running 
`systemctl status bluetooth`
I find the erroe reported in the log:
`Aug 10 13:08:35 CoreELEC bluetoothd[2931]: Unable to open adapter storage directory: /storage/.cache/bluetooth/43:45:C0:00:1F:AC`
So I checked the permission of the relevant folders:
```
CoreELEC:~ # ls -al ./storage/.cache/bluetooth
total 3
drwxr-xr-x    3 root     root          1024 Aug  5 13:07 .
drwxr-xr-x   11 1023     1023          1024 Aug  5 13:07 ..
drwx------    4 1023     1023          1024 Aug  5 13:18 43:45:C0:00:1F:AC
```
```
CoreELEC:~/.cache/bluetooth # ls -al ./storage/.cache
total 17
drwxr-xr-x   11 1023     1023          1024 Aug  5 13:07 .
drwxr-xr-x   16 1023     1023          1024 Aug  5 13:04 ..
drwxr-xr-x    3 root     root          1024 Aug  5 13:07 bluetooth
drwxr-xr-x    4 root     root          1024 Jan  1  2015 connman
drwxr-xr-x    2 root     root          1024 Aug 10 08:36 cores
drwxr-xr-x    3 1023     1023          1024 Aug  5 13:07 cron
-rw-r--r--    1 1023     1023             8 Aug 10 13:08 hostname
drwxr-xr-x    2 1023     1023          1024 Aug  5 13:01 kernel-overlays
drwxr-xr-x    3 1023     1023          1024 Aug  5 13:01 log
-rw-r--r--    1 1023     1023          2048 Aug 10 08:39 random.data
drwxr-xr-x    2 root     root          1024 Aug 10 13:09 services
----------    1 1023     1023           231 Apr 11  2019 shadow
drwxr-xr-x    2 root     root          1024 Aug 10 13:09 ssh
-rw-r--r--    1 1023     1023            33 Apr 11  2019 systemd-machine-id
drwxr-xr-x    2 root     root          1024 Aug  5 13:07 wireguard
```
If I run the following commands:
```
chown -R root:root /storage/.cache/bluetooth
chown -R root:root /storage/.cache
```
Then after rebooting CoreELEC, the bluetooth devices won't lose the connections with N1 anymore.
Does the problem arise from the CoreELEC orginal or this adapted CoreELEC for N1?

**Comment by flamingo7777** [comment]
用ssh登陆给这个地方.cache/bluetooth写入权限就没问题了

**Comment by lonecrane** [comment]
@flamingo7777 是的。不知道代码可否修正，不然每次都要弄一下。而且有些人开始并不知道，要走弯路。

**Comment by flamingo7777** [comment]
> @flamingo7777 是的。不知道代码可否修正，不然每次都要弄一下。而且有些人开始并不知道，要走弯路。

应该官方代码里就这么写的，其实N1目前最新也就9.2.3，最新的ce已经升级到9.2.4.1了，kodi18.8是kodi18系列最后一版了，感觉N1的ce更新也快到头了

**Comment by lonecrane** [comment]
@flamingo7777 kodi 18后面就出19，CoreELEC会跟着更新，N1的CoreELEC更新到到头是什么意思？

**Comment by flamingo7777** [comment]
> @flamingo7777 kodi 18后面就出19，CoreELEC会跟着更新，N1的CoreELEC更新到到头是什么意思？

目前最新的是9.2.4.1，以往最新的N1马上会更上，这次过了好久也没更新

**Comment by lonecrane** [comment]
@flamingo7777 我不懂软件开发，感觉这个项目维护起来还挺麻烦的，有些工作量，不是简单地打个补丁改下配置。可能大佬最近比较忙，我们耐心等等吧。其实平时这些小升级大家可能多数时候用不到。我最期待的还是kodi的功能升级，能支持外挂sup字幕和外挂音轨。当然大佬能抽时间维护升级最好不过。这个项目这么好，也挺受关注的，如果大佬没精力维护了，也希望有别的大佬能接过来。

**Comment by RuralHunter** [comment]
我这里权限是对的，你试过重装吗？其他人呢？

**Comment by flamingo7777** [comment]
> 我这里权限是对的，你试过重装吗？其他人呢？

我装的9.22，刷进emmc了，权限看过，蓝牙是有问题，改了权限后还是有问题，现在用2.4g遥控器，没有这个问题了

**Comment by RuralHunter** [comment]
刷emmc后权限问题基本是安装脚本的问题，直接装在u盘的应该不会有问题。

**Comment by lonecrane** [comment]
> 刷emmc后权限问题基本是安装脚本的问题，直接装在u盘的应该不会有问题。

大佬，我就是直接安装在U盘的。这样，我继续测试一阵子，如果找到了具体的形成条件再来报告。

**Comment by RuralHunter** [comment]
重刷一个u盘，启动后看一下权限：ls -l /storage/.cache
你的出现owner是1023很奇怪

**Comment by flamingo7777** [comment]
> 刷emmc后权限问题基本是安装脚本的问题，直接装在u盘的应该不会有问题。

嗯，谢谢大佬，坐等大佬更新最新固件！

**Comment by RuralHunter** [comment]
已经更新9.2.4.2

**Comment by RuralHunter** [comment]
已经更新9.2.4.2

**Comment by fireflycao** [comment]
> 已经更新9.2.4.2

请问是更新在内存里还是外部存储器？我的是内存装的，一直没敢更新。

**Comment by RuralHunter** [comment]
我这里只支持u盘的。

**Comment by RuralHunter** [comment]
我这里只支持u盘的。

**Comment by fireflycao** [comment]
请问emmc的去哪里找呢？

**Comment by lonecrane** [comment]
> 请问emmc的去哪里找呢？
这里有一个教程，直接翻到最后面一部分：
https://post.smzdm.com/p/ax02ve4d/

**Comment by lonecrane** [comment]
> 你的出现owner是1023很奇怪

大佬，我今天测试了一下9.2.4.2，问题没复现。如果以后发现再来报告。
