### ISSUE TITLE
请求大佬加入原盘BD-J菜单支持

### ISSUE THREAD

**Issue by Henshufu** [RuralHunter/CoreELEC#22]
官方论坛原帖https://discourse.coreelec.org/t/java-for-bd-j-menus/554/258 
每次发布新版本，论坛的vpeter大佬都会编译一个支持BD-J菜单的版本，但毕竟N1不是官方支持设备。
这个帖子里有相应的补丁和方法，希望大佬能加入这个功能。

**Comment by RuralHunter** [comment]
9.2.4.2中已增加

**Comment by 120318** [comment]
9.2.5中貌似没有？
