### ISSUE TITLE
请问怎么能只编译内核呢

### ISSUE THREAD

**Issue by kero990** [RuralHunter/CoreELEC#3]
如果我用了n1可用的内核，再配上通用的system能不能启动呢？
那么怎样编译能够只编译内核镜像，而不是整个系统呢？有没有这样的办法呢？
每次都编译整个CoreELEC实在是太费时间了。。。。。

**Comment by RuralHunter** [comment]
没有时间研究。

**Comment by tanst** [comment]
可以的，我一直都是直接替换 SYSTEM 文件大法升级系统的，反正内核万年 3.14，目前已经 9.2.3 了，没什么问题。
