### ISSUE TITLE
请问有考虑，CE加入 ipset, iptables的commment支持嘛？

### ISSUE THREAD

**Issue by 518512** [RuralHunter/CoreELEC#30]
请问有考虑，加入 ipset, iptables的commment支持嘛？。并且支持macvlan

**Comment by RuralHunter** [comment]
ipset, iptables已经支持。

**Comment by 518512** [comment]
好饿 谢谢

**Comment by matthuo333** [comment]
> ipset, iptables已经支持。

但是刚看工程下的linux.aarch64.conf 貌似和CE 官方的一致，没有配置ipset，iptables这些

**Comment by 518512** [comment]
> > ipset, iptables已经支持。
> 
> 但是刚看工程下的linux.aarch64.conf 貌似和CE 官方的一致，没有配置ipset，iptables这些

期待你的测试。我现在还没升级，因为之前是其他版本的CE，不知道怎样无能无损升级到RuralHunter 大佬版

**Comment by RuralHunter** [comment]
找个u盘刷一下。

**Comment by matthuo333** [comment]
> 找个u盘刷一下。

已试了，代理相关不能启动，替换别的内核，无问题。

**Comment by RuralHunter** [comment]
有什么错误？

**Comment by matthuo333** [comment]
> 有什么错误？
相关SSR+ ,PSW, Clash 均不能出海

**Comment by zcmi** [comment]
> 有什么错误？

大佬能教导一下如何修改conf文件，使其支持docker的openwrt出海吗？目前这个版本不太行
