### ISSUE TITLE
9.2.5 for s905x3 soc cpu 负载分配不均导致流媒体抖动

### ISSUE THREAD

**Issue by matthuo333** [RuralHunter/CoreELEC#33]
如题，在9.2.2 上就不会。4个核负载分配均匀。而9.2.5 出现cpu 随机出现0-100+%负载波动，导致1080P画质丢帧严重。

N1 也是如此。

**Comment by RuralHunter** [comment]
我这里n1没问题，其它SOC本来就不通用，有问题是正常的。
