### ISSUE TITLE
DTS音频直通输出有问题

### ISSUE THREAD

**Issue by joshddd** [RuralHunter/CoreELEC#37]
打开直通后在功放上大多数情况无法点亮DTS，只能使用PCM的两声道模拟输出。这个问题好像在9.2版本后就一直存在。以前的9.0版本直通选项下还有单独的DTS兼任等选项，9.2以后版本只有一个开关，不能选择。

**Comment by RuralHunter** [comment]
没有问题的，你可能没有打开高级选项
