### ISSUE TITLE
“reboot from emmc”无效

### ISSUE THREAD

**Issue by fnscar** [RuralHunter/CoreELEC#4]
电源选项里选择reboot from emmc，想要进入emmc里装的安卓系统，但重启后还是从U盘启动进入coreelec。
9.2.1版本。

**Comment by fnscar** [comment]
今天又试了下恩山论坛momokind的9.2版本，reboot from emmc是正常的。

**Comment by fooy** [comment]
我下了一个monokind的版本，把根目录下的那些*autoscript 和uEnv.ini, installtoemmc 全部覆盖拷贝过来就可以了，安装用install2emmc

**Comment by RuralHunter** [comment]
此版本不支持boot from emmc
