### ISSUE TITLE
CoreELEC 9.2.6 is now available.

### ISSUE THREAD

**Issue by 518512** [RuralHunter/CoreELEC#40]
Changes Since 9.2.5:

Fixed booting ODROID-HC4 from an ATA drive
Added Device Tree for Beelink GT mini A and GT1 mini
Added support for STK1160 analog TV tuner
Added ZRAM support (Amlogic)
**Added Bluetooth auto connect after boot and automatic switch to Bluetooth audio device**
Improved media handling and playback
Fixed CEC driver (Amlogic-NG)
Several small bug fixes
Fixed 8K HEVC playback
Added possibility to use BBR TCP congestion control algorithm

Downloads:
https://coreelec.org/#download

期待R大更新

**Comment by iamggs** [comment]
同等R大出手。

**Comment by cschongshi** [comment]
期待更新

**Comment by RuralHunter** [comment]
https://github.com/RuralHunter/CoreELEC/releases/tag/v9.2.6-N1
