### ISSUE TITLE
请大神帮助解决ASS字幕多字体和sup外挂字幕的问题

### ISSUE THREAD

**Issue by bluesea168** [RuralHunter/CoreELEC#42]
1.ass字幕即使把需要的多个字体文件（不能中文名称，要英文名称）放在/media/Fonts ，也不起作用。请大神看看下面的内容，是不是能够解决这个bug？
https://forum.libreelec.tv/thread/10874-custom-fonts-for-subtitles-issue/

2.sup字幕与电影同名是可以外挂，但是浏览的方式去看不见，过去taxigps应该有解决这个问题吧，是不是kodi后来的bug？
尝试为Kodi增加对.sup外挂字幕的支持
http://blog.sina.com.cn/s/blog_4ae08cc00102vzh3.html
https://github.com/xbmc/xbmc/commit/2e7dc772d4a78e8f94cf7b481ce7db23a6225587

希望大神看看能不能解决这2个问题。

**Comment by RuralHunter** [comment]
kodi 19.1有一个修正：
Fixed: detection of user fonts (in userdata/fonts) for ASS subtitles

**Comment by bluesea168** [comment]
> kodi 19.1有一个修正：
> Fixed: detection of user fonts (in userdata/fonts) for ASS subtitles

天啊，多少年过去了，kodi终于想去修正了。等ce19.1正式版出来后，找机会试试是真修补了还是假修补了吧。

**Comment by matthuo333** [comment]
> > kodi 19.1有一个修正：
> > Fixed: detection of user fonts (in userdata/fonts) for ASS subtitles
> 
> 天啊，多少年过去了，kodi终于想去修正了。等ce19.1正式版出来后，找机会试试是真修补了还是假修补了吧。

借问下，针对KODI19 的中文字幕库很少（opensubtitles 都还没支持），有推荐好用的么？

**Comment by bluesea168** [comment]
> > > kodi 19.1有一个修正：
> > > Fixed: detection of user fonts (in userdata/fonts) for ASS subtitles
> > 
> > 
> > 天啊，多少年过去了，kodi终于想去修正了。等ce19.1正式版出来后，找机会试试是真修补了还是假修补了吧。
> 
> 借问下，针对KODI19 的中文字幕库很少（opensubtitles 都还没支持），有推荐好用的么？

不是有字幕库插件可以用嘛，去taxigps的库看看，有能用的。字幕库插件自己改下地址。

**Comment by bluesea168** [comment]
ass字幕多字体测试后，应该基本上修复了。现在就是sup外挂还是看不见，如果有人能看看kodi16的时候taxigps他们的源代码就好了。

**Comment by matthuo333** [comment]
> > > > kodi 19.1有一个修正：
> > > > Fixed: detection of user fonts (in userdata/fonts) for ASS subtitles
> > > 
> > > 
> > > 天啊，多少年过去了，kodi终于想去修正了。等ce19.1正式版出来后，找机会试试是真修补了还是假修补了吧。
> > 
> > 
> > 借问下，针对KODI19 的中文字幕库很少（opensubtitles 都还没支持），有推荐好用的么？
> 
> 不是有字幕库插件可以用嘛，去taxigps的库看看，有能用的。字幕库插件自己改下地址。

taxigps 在哪呢？没找到呢。。。

**Comment by bluesea168** [comment]
> > > > > kodi 19.1有一个修正：
> > > > > Fixed: detection of user fonts (in userdata/fonts) for ASS subtitles
> > > > 
> > > > 
> > > > 天啊，多少年过去了，kodi终于想去修正了。等ce19.1正式版出来后，找机会试试是真修补了还是假修补了吧。
> > > 
> > > 
> > > 借问下，针对KODI19 的中文字幕库很少（opensubtitles 都还没支持），有推荐好用的么？
> > 
> > 
> > 不是有字幕库插件可以用嘛，去taxigps的库看看，有能用的。字幕库插件自己改下地址。
> 
> taxigps 在哪呢？没找到呢。。。

https://github.com/taxigps/xbmc-addons-chinese/tree/matrix
字幕库插件2.0.3看了，已经修补了.

后来我测试发现能找到字幕，但是下载老是失败，不知道什么原因。在电脑/ce/电视上测试的。

**Comment by bluesea168** [comment]
> > > > > kodi 19.1有一个修正：
> > > > > Fixed: detection of user fonts (in userdata/fonts) for ASS subtitles
> > > > 
> > > > 
> > > > 天啊，多少年过去了，kodi终于想去修正了。等ce19.1正式版出来后，找机会试试是真修补了还是假修补了吧。
> > > 
> > > 
> > > 借问下，针对KODI19 的中文字幕库很少（opensubtitles 都还没支持），有推荐好用的么？
> > 
> > 
> > 不是有字幕库插件可以用嘛，去taxigps的库看看，有能用的。字幕库插件自己改下地址。
> 
> taxigps 在哪呢？没找到呢。。。

字幕库插件开发者已经更新。
