### ISSUE TITLE
请问什么时候出19.2-Matrix_rc3的版本？

### ISSUE THREAD

**Issue by fireflycao** [RuralHunter/CoreELEC#47]
9.2.7还算稳定，但是有的搜刮器和字幕下载插件没法更新了。
多谢！

**Comment by microsgj** [comment]
同求，谢谢大佬

**Comment by alexzeng2014** [comment]
同求，谢谢大佬

**Comment by Henshufu** [comment]
先刷大佬的19.1，然后自己用官方19.2rc3的system文件替换原来的就行了。如果显示设备不支持HDR10+，CE19目前在N1上有播放HDR10+视频死机重启的问题。

**Comment by omiswang** [comment]
> 先刷大佬的19.1，然后自己用官方19.2rc3的system文件替换原来的就行了。如果显示设备不支持HDR10+，CE19目前在N1上有播放HDR10+视频死机重启的问题。

能给一下19.1的链接吗？大神百度的已经失效

**Comment by lonecrane** [comment]
> 先刷大佬的19.1，然后自己用官方19.2rc3的system文件替换原来的就行了。如果显示设备不支持HDR10+，CE19目前在N1上有播放HDR10+视频死机重启的问题。

大佬，我是小白，正在按照你说的方法尝试，现在到了“自己用官方19.2rc3的system文件替换原来的”这一步。我先用winrar解压img.gz得到img文件，然后用ext2explore-2.2.71.exe打开img文件，然后困惑是不知道哪些是system文件，也没有专门的system目录，可否麻烦指点
更新：用7-zip打开img.gz，得到的文件结构是0.fat, 1.img, 2，彻底蒙了

**Comment by lonecrane** [comment]
> 先刷大佬的19.1，然后自己用官方19.2rc3的system文件替换原来的就行了。如果显示设备不支持HDR10+，CE19目前在N1上有播放HDR10+视频死机重启的问题。

小白水平太次，在如下问题上卡壳：1、github提供了如下多个下载，应该下载哪个文件？
CoreELEC-Amlogic-ng.arm-19.2-Matrix_rc3-Generic.img.gz197 MB
CoreELEC-Amlogic-ng.arm-19.2-Matrix_rc3-LaFrite.img.gz197 MB
CoreELEC-Amlogic-ng.arm-19.2-Matrix_rc3-LePotato.img.gz198 MB
CoreELEC-Amlogic-ng.arm-19.2-Matrix_rc3-Odroid_C4.img.gz197 MB
CoreELEC-Amlogic-ng.arm-19.2-Matrix_rc3-Odroid_HC4.img.gz197 MB
CoreELEC-Amlogic-ng.arm-19.2-Matrix_rc3-Odroid_N2.img.gz197 MB
CoreELEC-Amlogic-ng.arm-19.2-Matrix_rc3-Radxa_Zero.img.gz197 MB
CoreELEC-Amlogic-ng.arm-19.2-Matrix_rc3.tar228 MB

2、如何解压所下载的img.gz文件？
我用winrar解压得到了img文件，但无法进一步打开所得的img文件；用7-zip打开img.gz，可以看到有3个文件，依次是0.fat（536M+），1.img（33M+），2（1M+）。但似乎都和以前写到U盘中的目录和文件不同。

3、哪些文件是system文件？

**Comment by Henshufu** [comment]
> > 先刷大佬的19.1，然后自己用官方19.2rc3的system文件替换原来的就行了。如果显示设备不支持HDR10+，CE19目前在N1上有播放HDR10+视频死机重启的问题。
> 
> 小白水平太次，在如下问题上卡壳：1、github提供了如下多个下载，应该下载哪个文件？
> CoreELEC-Amlogic-ng.arm-19.2-Matrix_rc3-Generic.img.gz197 MB
> CoreELEC-Amlogic-ng.arm-19.2-Matrix_rc3-LaFrite.img.gz197 MB
> CoreELEC-Amlogic-ng.arm-19.2-Matrix_rc3-LePotato.img.gz198 MB
> CoreELEC-Amlogic-ng.arm-19.2-Matrix_rc3-Odroid_C4.img.gz197 MB
> CoreELEC-Amlogic-ng.arm-19.2-Matrix_rc3-Odroid_HC4.img.gz197 MB
> CoreELEC-Amlogic-ng.arm-19.2-Matrix_rc3-Odroid_N2.img.gz197 MB
> CoreELEC-Amlogic-ng.arm-19.2-Matrix_rc3-Radxa_Zero.img.gz197 MB
> CoreELEC-Amlogic-ng.arm-19.2-Matrix_rc3.tar228 MB
> 
> 2、如何解压所下载的img.gz文件？
> 我用winrar解压得到了img文件，但无法进一步打开所得的img文件；用7-zip打开img.gz，可以看到有3个文件，依次是0.fat（536M+），1.img（33M+），2（1M+）。但似乎都和以前写到U盘中的目录和文件不同。
> 
> 3、哪些文件是system文件？

下载这个
CoreELEC-Amlogic-ng.arm-19.2-Matrix_rc3.tar 228 MB
其余操作参考
https://www.right.com.cn/forum/thread-1180672-1-1.html

不过官方不支持BD-J菜单，有此需求建议等R大更新，或者去官方论坛找vpeter大佬编译的镜像来替换，他最新编译的版本是RC2，说实话没有更新必要，因为N1的ng版本CE在显示设备不支持HDR10+的情况下播放HDR10+死机重启的bug并没有解决。RC3更新了HDR toSDR的修复，不知道有没有影响，没有测试。

**Comment by old1efty** [comment]
> > > 先刷大佬的19.1，然后自己用官方19.2rc3的system文件替换原来的就行了。如果显示设备不支持HDR10+，CE19目前在N1上有播放HDR10+视频死机重启的问题。
> > 
> > 
> > 小白水平太次，在如下问题上卡壳：1、github提供了如下多个下载，应该下载哪个文件？
> > CoreELEC-Amlogic-ng.arm-19.2-Matrix_rc3-Generic.img.gz197 MB
> > CoreELEC-Amlogic-ng.arm-19.2-Matrix_rc3-LaFrite.img.gz197 MB
> > CoreELEC-Amlogic-ng.arm-19.2-Matrix_rc3-LePotato.img.gz198 MB
> > CoreELEC-Amlogic-ng.arm-19.2-Matrix_rc3-Odroid_C4.img.gz197 MB
> > CoreELEC-Amlogic-ng.arm-19.2-Matrix_rc3-Odroid_HC4.img.gz197 MB
> > CoreELEC-Amlogic-ng.arm-19.2-Matrix_rc3-Odroid_N2.img.gz197 MB
> > CoreELEC-Amlogic-ng.arm-19.2-Matrix_rc3-Radxa_Zero.img.gz197 MB
> > CoreELEC-Amlogic-ng.arm-19.2-Matrix_rc3.tar228 MB
> > 2、如何解压所下载的img.gz文件？
> > 我用winrar解压得到了img文件，但无法进一步打开所得的img文件；用7-zip打开img.gz，可以看到有3个文件，依次是0.fat（536M+），1.img（33M+），2（1M+）。但似乎都和以前写到U盘中的目录和文件不同。
> > 3、哪些文件是system文件？
> 
> 下载这个
> CoreELEC-Amlogic-ng.arm-19.2-Matrix_rc3.tar 228 MB
> 其余操作参考
> https://www.right.com.cn/forum/thread-1180672-1-1.html
> 
> 不过官方不支持BD-J菜单，有此需求建议等R大更新，或者去官方论坛找vpeter大佬编译的镜像来替换，他最新编译的版本是RC2，说实话没有更新必要，因为N1的ng版本CE在显示设备不支持HDR10+的情况下播放HDR10+死机重启的bug并没有解决。RC3更新了HDR toSDR的修复，不知道有没有影响，没有测试。

--
测试了19.1的正式版替换19.2-RC3的SYSTEM，HDR10+仍然崩溃，退回到9.2.7用了，等19.2带BD-J菜单支持的正式版 :)

**Comment by RuralHunter** [comment]
19.2 released.
