### ISSUE TITLE
关于内核格式的问题

### ISSUE THREAD

**Issue by kero990** [RuralHunter/CoreELEC#5]
很荣幸上次您解答了我关于n1特殊性的问题，不过你把它关闭了，我不得不再问一个，希望不会太打扰您

上次您说“n1不支持lzo压缩的kernel，需要普通格式+initramfs”，我也看到您的option文件中这么写
KERNEL_TARGET="Image"

但是balbes150编译的系统都能够在n1上运行，他的option是这样的
KERNEL_TARGET="uImage.lzo"

而原版是这样
KERNEL_TARGET="Image.lzo"
我不懂这三者之间的差别，只知道原版肯定是不能运行的，那么这个"uImage.lzo"就是也可以用在n1上吗？

**Comment by RuralHunter** [comment]
有可能可以，我没试过，你有兴趣可以自己试一下。我觉得可能主要问题是有没有initramfs。至于kernel的格式区别，你可以谷歌或百度一下。
