### ISSUE TITLE
19.2版本如何刷入emmc中？

### ISSUE THREAD

**Issue by ghkghkghk** [RuralHunter/CoreELEC#53]
非常欣喜能使用19.2版本，想刷入N1的emmc中，不知道应该往U盘里增加什么文件，望大神指点。

**Comment by muccichung** [comment]
同求，试了之前19.1的方法不行。

**Comment by arubachen** [comment]
用root登录后输入ceemmc命令后提示：
Starting CoreELEC eMMC installation tool...

System is not supported: meson_gxl_s905d_phicomm_n1!
同求刷emmc方法，谢谢。

**Comment by grdxyxy** [comment]
我用了19.1的方法是可以的。

**Comment by muccichung** [comment]
> 我用了19.1的方法是可以的。

我也可以了。

**Comment by LexsionLee** [comment]
请各位大佬指导，19.1的方法在哪呢？

**Comment by LexsionLee** [comment]
我找到了，恩山大佬提供了[方法和相关文件](https://www.right.com.cn/forum/thread-4127217-1-1.html)

**Comment by hanlray** [comment]
> > 我用了19.1的方法是可以的。
> 
> 我也可以了。

我试了楼上恩山大佬的方法，启动时卡在logo上，能不能指点一下？

**Comment by tanst** [comment]
9.2.7 版本替换 SYSTEM 的方法还可以吗？

**Comment by RuralHunter** [comment]
no support.
