### ISSUE TITLE
蓝牙音箱连接问题

### ISSUE THREAD

**Issue by Subdue0** [RuralHunter/CoreELEC#57]
我用的天猫精灵，蓝牙连接，每次重启N1都要重新去蓝牙那里连接一下音箱才行，怎么不会自动连接，我用了好几个版本都不行，哪个版本是可以开机自动连蓝牙音箱的？

**Comment by alexzeng2014** [comment]
这里的19.3可以自动连接啊！

**Comment by Subdue0** [comment]
9.2.7好像连蓝牙都搜不到了，你们的可以吗

**Comment by flamingo7777** [comment]
> 9.2.7好像连蓝牙都搜不到了，你们的可以吗

不行，刷了19.4.1之后就可以自动连接了
