### ISSUE TITLE
19.3的一个BUG

### ISSUE THREAD

**Issue by lingyle** [RuralHunter/CoreELEC#61]
播放4K 漫威某些REMUX电影时候，画面不会自动全屏，需要切换一个音轨才能全屏。

**Comment by yanghonghao6789** [comment]
今天把coreelec播放器升级到19.3 搭配索尼电视遇到个问题 在coreelec播放器界面(hdmi2)关电视 电视会在几秒后开机 再次手动关机几秒后还是会开机 ，如果回到电视主界面或者其他非coreelec界面可以正常关机， 感觉在coreelec界面下关机，播放器还在向电视发送信号 吗(类似电视关机状态下，给coreelec播放器通电，然后电视会随着播放器启动开机)。

**Comment by RuralHunter** [comment]
try 19.4
