### ISSUE TITLE
关掉盒子LED

### ISSUE THREAD

**Issue by fkpwolf** [RuralHunter/CoreELEC#67]
https://www.right.com.cn/forum/thread-4017373-1-1.html

这里有关掉LED的方法，我试过，没有作用，应该是kernel device tree没有定义led的位置么？

**Comment by yanghonghao6789** [comment]
今天把coreelec播放器升级到19.3 搭配索尼电视遇到个问题 在coreelec播放器界面(hdmi2)关电视 电视会在几秒后开机 再次手动关机几秒后还是会开机 ，如果回到电视主界面或者其他非coreelec界面可以正常关机， 感觉在coreelec界面下关机，播放器还在向电视发送信号 吗(类似电视关机状态下，给coreelec播放器通电，然后电视会随着播放器启动开机)。
