### ISSUE TITLE
[BUG] N1 Player - HDMI2.0线缆 - 9000F sound bar  - Sony 9000F 电视关闭后20秒左右屏幕被唤醒

### ISSUE THREAD

**Issue by loveofyou** [RuralHunter/CoreELEC#75]
**[BUG] N1 Player - HDMI2.0线缆 - 9000F sound bar  - Sony 9000F 电视关闭后20秒左右屏幕被唤醒**

N1盒子U盘引导CorElec,使用HDMI2.0线缆连接sony 9000f回音壁透传至 sony 9000f 电视机,
电视Android版本8.0.使用电视遥控CEC进行操作盒子.

电视机使用遥控关闭后大约20秒左右被重新唤醒打开,行为可复现.

**Comment by pcx20010** [comment]
某宝买个cec屏蔽器解决

**Comment by RuralHunter** [comment]
在设置的外设选项里把CEC的几个选项调一下看看。我记得以前我也碰到过，调了哪个选项就好了。

**Comment by loveofyou** [comment]
> 

正解 在kodi cec设置没修改唤醒设置后该现象未再出现
