### ISSUE TITLE
[BUG] 19.x 会自动唤醒电视

### ISSUE THREAD

**Issue by 4ft35t** [RuralHunter/CoreELEC#84]
### Describe the bug

在 CoreELEC 界面按电视遥控器的待机，大概5秒后会自动唤醒电视。
### To Reproduce
1.  系统默认设置
1. 在 CoreELEC 界面按电视遥控器关机
2. 5 秒后电视开机

### Informations
 - 电视：Sony KD-55X85J
 - 19.1、19.3、19.4 、19.4.1 均存在此问题

### Log file

2022-09-12 05:47:41.171 T:4655     INFO <general>: OnSleep: Running sleep jobs
2022-09-12 05:47:41.410 T:4655    ERROR <general>: Keymapping error: no such action 'lirc.stop' defined
2022-09-12 05:47:47.361 T:4655     INFO <general>: OnWake: Running resume jobs

### Additional context
- momokind 的 9.2.2 写入 emmc 无此问题
- 关机前切换到其他 HDMI，或者系统主界面，部分版本不会自动开机。
- 19.4.1 切到别的输入源关机，大概10秒后开机
- 19.4 切到别的输入源关机，大概10秒后开机
- 19.3 切到别的 HDMI 关机，不会开机; 切系统主界面关机，大概10秒后开机

**Comment by 4ft35t** [comment]
完整日志
http://ix.io/4agL

**Comment by yanghonghao6789** [comment]
> 
打开设置--输入-外设-cec adapter-更改以下几个设置：启动时开启的设备 选项改为无，关机时关闭的设备 选项改为无，电视关闭时 选项改为忽略。  最后一项就解决电视关机几秒后再开机的问题，前两项你看着改 不动也行

**Comment by 4ft35t** [comment]
> > 
> 
> 打开设置--输入-外设-cec adapter-更改以下几个设置：启动时开启的设备 选项改为无，关机时关闭的设备 选项改为无，电视关闭时 选项改为忽略。 最后一项就解决电视关机几秒后再开机的问题，前两项你看着改 不动也行

设置-系统-输入-外设-cec adapter，`电视关闭时`从`待机`切换到`暂停播放`，问题解决。
