### ISSUE TITLE
无法从内部emmc启动

### ISSUE THREAD

**Issue by edgery** [RuralHunter/CoreELEC#9]
u盘写人版本9.2.2，已可以正常运行coreelec；
目前内部emmc是yyf盒子系统，插coreelec的u盘可以正常从u盘启动coreelec，但是在coreelec电源选择"reboot from emmc or..."想重启进内部yyf盒子系统时，结果重启还是进入了coreelec界面，没有进内部盒系统。原先是点这个选项是可以插着u盘是可以进emmc盒子系统的，但9.2.2'这版却不行了。
请大神协助解决一下，双系统切换是硬需求，谢谢。

**Comment by fnscar** [comment]
#4

**Comment by edgery** [comment]
> #4
经过摸索，已解决，见《让N1 CoreELEC支持从U盘启动、eMMC启动、支持双系统切换》http://blog.qint.top/archives/11/

**Comment by RuralHunter** [comment]
链接: https://pan.baidu.com/s/1TZFriombQVYYlYcmxcOTNw 提取码: jbib
这个升级包试一下，一样放在/storage/.update/下面重启就行。
