### ISSUE TITLE
[BUG]网络感觉有问题，播放alist的阿里云盘，网速最高7M，平均5-6M

### ISSUE THREAD

**Issue by LastNiceGuy** [RuralHunter/CoreELEC#93]
RT，不管是直接插网线还是wifi，网速最高都是7M，平均5-6M的样子（有线是千兆，无线是5G ac），导致播放原盘一直卡顿。
但是刷了安卓系统不管是kodi挂载播放还是阿里云盘，都能到10m+，实现稳定的4k原盘播放。

可以麻烦定位下问题吗？

**Comment by LastNiceGuy** [comment]
在coreelec系统里面找到一个类似问题，并且貌似已经被解决了，有时间的话麻烦帮忙看下。
https://discourse.coreelec.org/t/odroid-n2-very-slow-lan-download-in-1gb-network/20439/8

**Comment by mackon666** [comment]
我昨天晚上也发现了，我以为是n1同时挂着alist又播放超过30G的视频运行不动了才会这样，然后电视上装了kodi21连着n1播放60G的电影都不卡。

**Comment by RuralHunter** [comment]
Try this:
链接: https://pan.baidu.com/s/1cx1VSlMyxZGVSNvxma3vRg?pwd=3g1e 提取码: 3g1e
